const teams=[{name:"Clutza",tag:"CLT",points:182,logo:"C"},{name:"Nova X",tag:"NVX",points:166,logo:"N"},{name:"Revenant",tag:"RVN",points:151,logo:"R"},{name:"Volt",tag:"VLT",points:139,logo:"V"}];
const roster=[{name:"Clutza Viper",role:"IGL",num:"01",meta:"In-game leader • Captain"},{name:"Clutza Raze",role:"Rusher",num:"07",meta:"Entry fragger"},{name:"Clutza Nox",role:"Assaulter",num:"11",meta:"Support & assault"},{name:"Clutza Scope",role:"Sniper",num:"21",meta:"Long-range specialist"}];
const tournaments=[{name:"Clutza Open Series #04",status:"open",date:"Oct 18, 2026",teams:"32 / 64",prize:"₹50,000"},{name:"Clutza Community Cup",status:"live",date:"Live now",teams:"48 teams",prize:"₹25,000"},{name:"Summer Clash 2026",status:"done",date:"Aug 22, 2026",teams:"64 teams",prize:"₹1,00,000"}];
const nav=[["home","Home"],["team","Team"],["tournaments","Tournaments"],["results","Results"],["about","About"]];
let route=location.hash.slice(1)||"home";
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function layout(content){return `<div class="shell"><header class="topbar"><div class="brand"><div class="logo">C</div>CLUTZA <span class="muted">ESPORTS</span></div><nav class="nav">${nav.map(n=>`<button class="${route===n[0]?"active":""}" onclick="go('${n[0]}')">${n[1]}</button>`).join("")}</nav><div class="actions"><button class="btn ghost" onclick="go('organizer')">Organizer</button><button class="btn primary" onclick="openRegister()">Register Team</button></div></header>${content}<div class="mobile-nav">${nav.slice(0,4).map(n=>`<button class="${route===n[0]?"active":""}" onclick="go('${n[0]}')">◉<br>${n[1]}</button>`).join("")}<button onclick="go('organizer')">▣<br>Manage</button></div></div>`}
function home(){return layout(`<main><section class="hero"><div><div class="eyebrow">Free Fire Esports Organization</div><h1>Built to compete.<br>Ready to win.</h1><p>Clutza Esports is a competitive Free Fire organization focused on high-level competition, disciplined teams and a growing esports community.</p><div class="hero-actions"><button class="btn primary" onclick="go('team')">Explore the team →</button><button class="btn" onclick="go('tournaments')">Browse tournaments</button></div></div><div class="hero-card"><span class="badge">TEAM PROFILE</span><div class="card-title">A competitive home for players, fans and tournaments.</div><p class="muted">Team portfolio + tournament operations in one PWA-ready experience.</p><div class="stat-row"><div class="stat"><b>04</b><span>Active players</span></div><div class="stat"><b>18</b><span>Podiums</span></div><div class="stat"><b>12</b><span>Events hosted</span></div></div></div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Featured</div><h2>Our roster</h2></div><button class="btn" onclick="go('team')">View full team</button></div><div class="grid4">${roster.map(p=>player(p)).join("")}</div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Compete</div><h2>Upcoming tournaments</h2></div><button class="btn" onclick="go('tournaments')">All tournaments</button></div><div class="grid">${tournaments.slice(0,3).map(t=>tour(t)).join("")}</div></section></main>${footer()}`)}
function player(p){return `<article class="panel player"><span class="number">${p.num}</span><span class="role">${p.role}</span><h3>${p.name}</h3><span class="muted">${p.meta}</span></article>`}
function tour(t){return `<article class="panel tournament"><span class="pill ${t.status}">${t.status==="live"?"● LIVE":t.status==="open"?"REGISTRATION OPEN":"COMPLETED"}</span><h3>${t.name}</h3><span class="muted">${t.date} · ${t.teams}</span><div class="bottom"><b>${t.prize}</b><button class="btn" onclick="openTournament('${t.name}')">Details</button></div></article>`}
function team(){return layout(`<main><section class="section"><div class="eyebrow">The organization</div><h1>More than a roster.</h1><p class="muted" style="max-width:700px;line-height:1.7">Clutza Esports is built around competitive Free Fire, player development, community and professionally managed tournaments.</p></section><section class="section"><div class="section-head"><div><div class="eyebrow">Players</div><h2>Active roster</h2></div></div><div class="grid4">${roster.map(player).join("")}</div></section><section class="section"><div class="section-head"><div><div class="eyebrow">Journey</div><h2>Our story</h2></div></div><div class="panel timeline"><div class="event"><b>2024</b><h3>Clutza founded</h3><p class="muted">Started as a competitive Free Fire squad with a focus on structured team play.</p></div><div class="event"><b>2025</b><h3>First major podiums</h3><p class="muted">Expanded the roster and began participating in larger community circuits.</p></div><div class="event"><b>2026</b><h3>Organization era</h3><p class="muted">Built a stronger competitive program and began hosting tournaments.</p></div></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">Honors</div><h2>Achievements</h2></div></div><div class="grid">${[["🏆","Regional Cup — Champions","2026"],["🥇","Community League — 1st Place","2026"],["🥈","Winter Clash — Runner-up","2025"],["🏅","18 podium finishes","Career"]].map(x=>`<div class="panel trophy"><div class="trophy-icon">${x[0]}</div><div><b>${x[1]}</b><div class="muted">${x[2]}</div></div></div>`).join("")}</div></section></main>${footer()}`)}
function tournamentsPage(){return layout(`<main><section class="section"><div class="eyebrow">Tournament Hub</div><h1>Compete. Manage. Repeat.</h1><p class="muted">Discover Clutza-hosted competitions and follow every stage from registration to final standings.</p><div class="hero-actions"><button class="btn primary" onclick="openRegister()">Register your team</button></div></section><section class="section"><div class="grid">${tournaments.map(tour).join("")}</div></section></main>${footer()}`)}
function results(){return layout(`<main><section class="section"><div class="eyebrow">Competitive record</div><h1>Results & standings</h1><p class="muted">A single place for tournament results, points and team performance.</p></section><section class="section"><div class="panel table-wrap"><table class="table"><thead><tr><th>#</th><th>Team</th><th>Booyah</th><th>Placement</th><th>Kills</th><th>Points</th></tr></thead><tbody>${teams.map((t,i)=>`<tr><td class="rank">${i+1}</td><td><b>${t.name}</b><div class="muted">${t.tag}</div></td><td>${12-i*2}</td><td>${34+i*7}</td><td>${91-i*9}</td><td><b>${t.points}</b></td></tr>`).join("")}</tbody></table></div></section><section class="section"><div class="section-head"><div><div class="eyebrow">Bracket</div><h2>Playoff bracket</h2></div></div><div class="bracket"><div>${["Clutza 2 - 0 Volt","Nova X 2 - 1 Echo"].map(m=>match(m)).join("")}</div><div>${["Clutza 2 - 1 Nova X"].map(m=>match(m)).join("")}</div><div>${["FINAL · Clutza 3 - 2 Revenant"].map(m=>match(m)).join("")}</div></div></section></main>${footer()}`)}
function match(m){return `<div class="match"><div class="teamline">${m.split(" ")[0]} <b>✓</b></div><div class="muted">${m}</div></div>`}
function about(){return layout(`<main><section class="section"><div class="eyebrow">Platform prototype</div><h1>One platform for the organization.</h1><div class="grid"><div class="panel"><h3>Team portfolio</h3><p class="muted">Roster, journey, achievements, results, media and brand information.</p></div><div class="panel"><h3>Tournament operations</h3><p class="muted">Registration, scheduling, results, standings, brackets and announcements.</p></div><div class="panel"><h3>PWA-ready</h3><p class="muted">Designed mobile-first and structured for installable web-app delivery.</p></div></div></section></main>${footer()}`)}
function organizer(){return `<div class="dashboard"><aside class="sidebar"><div class="brand" style="margin:8px 10px 30px"><div class="logo">C</div>CLUTZA</div><p class="side-title">Workspace</p><div class="side"><button class="active">▦ Overview</button><button onclick="toast('Tournament creator opened')">🏆 Tournaments</button><button onclick="toast('Team manager opened')">👥 Teams</button><button onclick="toast('Match scheduler opened')">⚔ Matches</button><button onclick="toast('Announcement manager opened')">📣 Announcements</button></div><p class="side-title" style="margin-top:30px">Public</p><div class="side"><button onclick="go('home')">↗ View website</button></div></aside><section class="dash-main"><div class="section-head"><div><div class="eyebrow">Organizer workspace</div><h1 style="margin:6px 0">Dashboard</h1><p class="muted">Tournament operations overview</p></div><button class="btn primary" onclick="openCreate()">+ Create tournament</button></div><div class="kpis"><div class="panel kpi"><b>06</b><span>Active tournaments</span></div><div class="panel kpi"><b>128</b><span>Registered teams</span></div><div class="panel kpi"><b>42</b><span>Matches today</span></div><div class="panel kpi"><b>₹2.4L</b><span>Total prize pools</span></div></div><div class="grid"><div class="panel"><div class="eyebrow">Live now</div><h3>Clutza Community Cup</h3><p class="muted">48 teams · Round 4 · 16:30</p><button class="btn" onclick="toast('Opening live match control')">Manage matches</button></div><div class="panel"><div class="eyebrow">Registrations</div><h3>Clutza Open Series #04</h3><p class="muted">32 / 64 teams registered</p><button class="btn" onclick="toast('Opening registration list')">Review teams</button></div><div class="panel"><div class="eyebrow">Announcement</div><h3>Match schedule published</h3><p class="muted">Round 2 schedule was published 12 minutes ago.</p><button class="btn" onclick="toast('Announcement editor opened')">Edit</button></div></div><section style="margin-top:30px"><div class="section-head"><h2>Today's matches</h2><span class="muted">Sep 22, 2026</span></div><div class="panel table-wrap"><table class="table"><thead><tr><th>Match</th><th>Round</th><th>Teams</th><th>Status</th><th>Action</th></tr></thead><tbody>${["M-041","M-042","M-043","M-044"].map((m,i)=>`<tr><td><b>${m}</b></td><td>Round ${i+1}</td><td>${i%2?"Nova X vs Volt":"Clutza vs Revenant"}</td><td><span class="pill ${i<2?"live":"open"}">${i<2?"LIVE":"SCHEDULED"}</span></td><td><button class="btn" onclick="toast('Match control opened')">Open</button></td></tr>`).join("")}</tbody></table></div></section></section></div>`}
function footer(){return `<footer class="footer"><span>© 2026 Clutza Esports</span><span>Competitive Free Fire · Community · Tournaments</span></footer>`}
function go(r){route=r;location.hash=r;render();scrollTo(0,0)}
function render(){document.getElementById("app").innerHTML=route==="home"?home():route==="team"?team():route==="tournaments"?tournamentsPage():route==="results"?results():route==="about"?about():route==="organizer"?organizer():home()}
function toast(msg){const x=document.createElement("div");x.className="toast";x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function modal(html){const x=document.createElement("div");x.className="modal";x.innerHTML=`<div class="modal-box">${html}</div>`;document.body.appendChild(x);x.addEventListener("click",e=>{if(e.target===x)x.remove()})}
function openRegister(){modal(`<div class="modal-head"><div><div class="eyebrow">Tournament registration</div><h2>Register your team</h2></div><button class="close" onclick="this.closest('.modal').remove()">×</button></div><form class="form-grid" onsubmit="event.preventDefault();this.closest('.modal').remove();toast('Registration submitted — prototype only')"><div class="field"><label>TEAM NAME</label><input required placeholder="Your team name"></div><div class="field"><label>CAPTAIN IGN</label><input required placeholder="Captain IGN"></div><div class="field"><label>CAPTAIN UID</label><input required placeholder="8–12 digit UID"></div><div class="field"><label>CONTACT</label><input required placeholder="WhatsApp / email"></div><div class="field full"><label>SELECT TOURNAMENT</label><select><option>Clutza Open Series #04</option><option>Clutza Community Cup</option></select></div><div class="field full"><label>ROSTER</label><input placeholder="Player 2, Player 3, Player 4, Substitute"></div><div class="field full"><button class="btn primary">Submit registration</button></div></form>`)}
function openTournament(name){modal(`<div class="modal-head"><div><div class="eyebrow">Tournament details</div><h2>${esc(name)}</h2></div><button class="close" onclick="this.closest('.modal').remove()">×</button></div><div class="grid"><div class="panel"><span class="muted">FORMAT</span><h3>Squad · 4 players</h3></div><div class="panel"><span class="muted">PRIZE POOL</span><h3>₹50,000</h3></div><div class="panel"><span class="muted">CHECK-IN</span><h3>30 min before</h3></div></div><div style="margin-top:18px"><button class="btn primary" onclick="this.closest('.modal').remove();openRegister()">Register team</button></div>`)}
function openCreate(){modal(`<div class="modal-head"><div><div class="eyebrow">Organizer</div><h2>Create tournament</h2></div><button class="close" onclick="this.closest('.modal').remove()">×</button></div><form class="form-grid" onsubmit="event.preventDefault();this.closest('.modal').remove();toast('Tournament created — prototype only')"><div class="field full"><label>TOURNAMENT NAME</label><input required placeholder="e.g. Clutza Open Series #05"></div><div class="field"><label>FORMAT</label><select><option>Squad</option><option>Duo</option><option>Solo</option></select></div><div class="field"><label>MAX TEAMS</label><input type="number" value="64"></div><div class="field"><label>START DATE</label><input type="date"></div><div class="field"><label>PRIZE POOL</label><input placeholder="₹1,00,000"></div><div class="field full"><label>RULES / DESCRIPTION</label><input placeholder="Short tournament description"></div><div class="field full"><button class="btn primary">Create tournament</button></div></form>`)}
window.addEventListener("hashchange",()=>{route=location.hash.slice(1)||"home";render()});
if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>{});
render();